/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AltiSkinTool;

import java.awt.EventQueue;

import AltiSkinTool.ui.PlaneView;

public class App {

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    PlaneView window = new PlaneView(
                            "D:\\SteamLibrary\\steamapps\\common\\Altitude\\app\\resources\\dist");
                    // PlaneView window = new PlaneView("C:\\Program Files
                    // (x86)\\Steam\\steamapps\\common\\Altitude\\resources\\dist");
                    window.frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

    }
}
