/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AltiSkinTool;

import java.awt.EventQueue;
import java.util.Properties;

import AltiSkinTool.ui.PlaneView;
import AltiSkinTool.util.Config;

public class App {

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Properties prop = Config.getProperties();
                    prop.getProperty("dist_path");
                    PlaneView window = new PlaneView(prop.getProperty("dist_path"));
                    window.frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

    }
}
